name: fnds_monorepo

packages:
  - apps/**
  - packages/**

scripts:
  debug-demo:
    name: debug-demo
    description: Run Debug Mode for Demo
    run: melos exec --scope demo -- flutter run
  dry-publish-cli:
    name: dry-publish-cli
    description: Dry run publish for CLI
    run: melos exec --scope fnds_cli -- dart pub publish --dry-run
  publish-cli:
    name: publish-cli
    description: run publish for CLI
    run: melos exec --scope fnds_cli -- dart pub publish