name: fnds_monorepo
publish_to: none
environment:
  sdk: ^3.6.0

workspace:
  - packages/fnds_kit
  - packages/fnds_cli
  - packages/fnds_logger
  - apps/demo
  - apps/cli
  
dev_dependencies:
  melos: ^6.3.2
