name: fnds_cli
description: Another starting point for interactive CLI using Dart, inspired by AstroJS CLI.
resolution: workspace
version: 0.2.0
repository: https://github.com/a-man-called-q/fnds

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  ansi_strip: ^0.1.1+1
  

dev_dependencies:
  chalkdart: ^3.0.4
  lints: ^5.0.0
  test: ^1.24.0
