name: cli
description: A sample command-line application.
version: 1.0.0
resolution: workspace
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  chalkdart: ^3.0.4
  ansi_strip: ^0.1.1+1
  path: ^1.8.0
  fnds_cli:
    path: ../../packages/fnds_cli
