name: fnds_logger
description: Lightweight, plug-and-play Drift-based logging package for Flutter apps.
version: 1.0.0
resolution: workspace
homepage: https://github.com/a-man-called-q/fnds # replace with your actual URL
repository: https://github.com/a-man-called-q/fnds
issue_tracker: https://github.com/a-man-called-q/fnds/issues

environment:
  sdk: '^3.7.2'

dependencies:
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path: ^1.8.0
  path_provider: ^2.1.0
  sqlite3: ^2.7.5
  meta: ^1.9.1
  universal_io: ^2.2.2

dev_dependencies:
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  test: ^1.25.15
